# Generated by Django 5.1.1 on 2024-10-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('isi', models.TextField()),
                ('pilih_kategori', models.CharField(choices=[('py', 'Pyhton'), ('js', 'Java Script'), ('css', 'Cascading Style Sheets')], max_length=10)),
            ],
        ),
    ]
