# Generated by Django 5.1.1 on 2024-10-22 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_kategori_alter_article_pilih_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gambar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
